location = /index.html { expires -1; }
location = /ngsw.json { expires -1; }
location = /ngsw-worker.js { expires -1; }
location = /manifest.json { expires -1; }
location ~* \.(js|css|woff2?)$ { expires 1y; }
