-- V1: Baseline schema for oasis_spots.
-- This migration reproduces the exact schema already present in the live production
-- database (captured via pg_dump --schema-only on PostgreSQL 16.15).
-- On a FRESH database, Flyway executes this migration to create the schema.
-- On the EXISTING production database, Flyway adopts this schema via baseline
-- (spring.flyway.baseline-on-migrate=true, spring.flyway.baseline-version=1):
-- this script is registered as already applied and is NEVER executed against it.
CREATE TABLE oasis_spots (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at   timestamp(6) without time zone NOT NULL,
    is_available boolean NOT NULL,
    latitude     double precision NOT NULL,
    longitude    double precision NOT NULL,
    name         character varying(255) NOT NULL,
    osm_node_id  bigint,
    type         smallint NOT NULL,
    updated_at   timestamp(6) without time zone,
    CONSTRAINT oasis_spots_pkey PRIMARY KEY (id),
    CONSTRAINT oasis_spots_type_check CHECK (type >= 0 AND type <= 2),
    -- The unique constraint name below is Hibernate's auto-generated name
    -- (from the ddl-auto era). It is preserved verbatim, unchanged, so that a
    -- freshly migrated database is byte-for-byte identical (constraint names
    -- included) to the existing production database that this migration
    -- adopts via baseline.
    CONSTRAINT ukjssgqmrp5b61xhucijvymjle1 UNIQUE (osm_node_id)
);
