spring:
  application:
    name: backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/urban_oasis}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false

overpass:
  sync:
    cron: "0 0 3,15 * * *"

server:
  port: ${PORT:8080}
