spring:
  application:
    name: backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/urban_oasis}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: false

server:
  port: ${PORT:8080}
